### ISSUE TITLE
Exception thrown from events.js

### ISSUE THREAD

**Issue by Barbarrosa** [leebradley/wikiedit-monitor#12]
I encountered an exception  thrown by `events.js` on line 154. This completely stopped and crashed the `editlog.js` program.

I suspect that part of the stack trace comes from Node's own source code.

I'm including the preceding lines to assist with addressing the issue.

```
Mercurim             | Oosterbeek                     | /* Osterbeek School */        
95.144.135.119       | North East Derbyshire          |                               
Geraldshields11      | Sienna Miller                  | /* Personal life */ Copyedit (
Wikimandia           | Esme Howard, 1st Baron Howard  |                               
***** Requesting 38 diffs from Wikipedia
Notecardforfree      | Real progress                  | Removed sections needed tag --
2601:C1:8000:E7C0:19 | Emory University               | /* Further reading */         
ZappaOMati           | Clay Greenfield                | /* Camping World Truck Series 
***** Wikipedia returned in 0.5s
***** INSERTED 9 rows in 7ms
Zacourie             | Abomination of desolation      | /* Christological */          
Irarod3              | Dale Larson                    | /* Education */               
Savvyjack23          | Talk:Giulio Tonti              |                               
SlimVirgin           | Mass sexual assault in Egypt   | ce, restored a quote          
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect EINVAL 208.80.154.224:443
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
```

**Comment by ameliabradley** [comment]
What version of nodejs are you using? On what platform?

**Comment by Barbarrosa** [comment]
I'm using [version 5.5](https://nodejs.org/docs/v0.5.5/) on Fedora 23

**Comment by Barbarrosa** [comment]
I also just encountered this exception:

```
I dream of horses    | Political Marxism              | v1.38 - [[WP:WCW]] project (Ta
Scsbot               | Wikipedia:WikiProject Articles | edited by robot:
archiving Feb
Jweiss11             | User talk:10stone5             | /* Drexel Dragons men's lacros
Cornerstonepicker    | Ed Sheeran                     | /* top */ now that he's a Gram
Ser Amantio di Nicol | Woman-Wise                     | add category using [[Project:A
***** Requesting 23 diffs from Wikipedia
2602:302:D19E:2220:F | Mission San Luis Obispo de Tol |                               
***** Wikipedia returned in 0.41s
***** INSERTED 21 rows in 13ms
Fuddle               | Template:Video processing      |                               
Ser Amantio di Nicol | Woman Against Woman            | /* External links */add catego
202.62.17.110        | IPhone 6S                      |                               
2602:306:3062:D180:F | Drexel Dragons men's lacrosse  | /* Annual record */           
Ser Amantio di Nicol | Woman Doctor (film)            | /* External links */add catego
KasparBot            | Alphons Diepenbrock            | migrating [[Wikipedia:Personda
Kytabu               | 2016 Australian GT Championshi | /* top */ Wrong date          
Ser Amantio di Nicol | Women Are Like That            | /* External links */add catego
2601:3C9:0:925B:AD62 | Shy Glizzy                     | /* Mixtapes */                
Liamkasbar           | Edward C. Mann                 |                               
2602:30A:C0FD:1BD0:5 | User:Words44/sandbox           |                               
SchreiberBike        | Antsiranana Province           | Lower case for species common 
Ser Amantio di Nicol | Women Are Trouble              | add category using [[Project:A
Aruppillai           | Superconducting wire           |                               
Ser Amantio di Nicol | Women Everywhere               | /* External links */add catego
Marek69              | Republic of Macedonia          | /* World War II period */ adde
Impendingdoom240     | Abated mass of flesh           |                               
Ser Amantio di Nicol | Women Love Once                | /* External links */add catego
66.81.253.181        | The D Train                    | update                        
Caden                | Talk:Harry James discography   | add                           
Bluesangrel          | Ionikos Nikaias B.C.           | /* Classification 2008–09 seas
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read EINVAL
    at exports._errnoException (util.js:856:11)
    at TLSWrap.onread (net.js:544:26)
```

**Comment by Barbarrosa** [comment]
I suspect that this is an encoding issue. I also noticed that [a newer version of socket.io](http://socket.io/blog/socket-io-1-0-3/) purports to fix a UTF-8 encoding problem.

**Comment by ameliabradley** [comment]
I've been running the script all day and it hasn't encountered any problems. Are you on the version of the socket library that's in the package.json file?

**Comment by Barbarrosa** [comment]
I traced the `TLSWrap.onread` error back through `WebSocket.js`. [Here's the actual line](https://github.com/nodejs/node/blob/v5.5.0/lib/net.js#L544) that seems to be triggering the error.

This appears to route through [JSStream::DoRead](https://github.com/nodejs/node/blob/v5.5.0/src/js_stream.cc#L152) or [JSStream::ReadBuffer](https://github.com/nodejs/node/blob/v5.5.0/src/js_stream.cc#L177).

**Comment by Barbarrosa** [comment]
I tried different versions of the socket library, but both of the above errors were triggered with the version in the `package.json` file.

**Comment by Barbarrosa** [comment]
My instance crashed with this error today:

```
***** Requesting 29 diffs from Wikipedia
Neptune's Trident    | John David California          |                               
***** Wikipedia returned in 0.7s
***** INSERTED 29 rows in 13ms
Wonderwizard         | Scarlets                       | /* Current kit */             
80.192.78.230        | Iron Heights Penitentiary      | /* Video game */              
203.106.148.17       | 2016 Selangor FA season        | /* Statistics */              
KasparBot            | William McFee                  | migrating [[Wikipedia:Personda
Vipinhari            | User talk:204.185.34.74        | Message re. [[Women in the mil
TheBlinkster         | User:TheBlinkster/sandbox      | /* Events before disappearance
NFLisAwesome         | Ryan Newman                    | /* Daytona 500 */ + start     
NatureBoyMD          | User:NatureBoyMD/temp          | /* League champions */        
Eni.Sukthi.Durres    | List of Albania international  | /* See also */                
Maxal                | Bell polynomials               | /* Ordinary Bell polynomial */
HighBallStepper      | Blunderbuss                    | /* In popular culture */  Fixe
Wwikix               | Buren                          | /* Demographics */            
124.123.81.194       | List of Chief Ministers of Aru |                               
74.77.48.217         | 2015 Stanley Cup Finals        | /* Chicago Blackhawks */      
Champaign Supernova  | Mark Kirk                      | /* 2010 election */           
BattyBot             | Talk:The Go-Go's               | /* top */[[WP:AWB/GF#Talk page
Ser Amantio di Nicol | Chillicothe, Iowa              | /* External links */fix Common
***** Socket Disconnected
***** Socket Reconnecting... 1000
***** Socket Reconnecting... 2000
***** Socket Reconnecting... 4000
***** Socket Reconnecting... 8000
***** Socket Reconnecting... 16000
***** Socket Reconnecting... 32000
***** Socket Reconnecting... 64000
***** Socket Reconnecting... 128000
***** Socket Reconnecting... 256000
***** Socket Reconnecting... 512000
```

The last `socketdata` record has a timestamp of 02/19/2016 @ 5:29pm (UTC).

**Comment by Barbarrosa** [comment]
I encountered the `onread` issue again and verified that the exit status is `1`.

Here's the output:

```
BattyBot             | Talk:Agnes de Mille            | /* top */[[WP:AWB/GF#Talk page
DeltaQuadBot         | User:DeltaQuad/UAA/Wait        | [[User:DeltaQuadBot|DeltaQuadB
SNUGGUMS             | Wikipedia:Administrators' noti | Self-revert; just saw thread w
***** Requesting 20 diffs from Wikipedia
***** Wikipedia returned in 1.15s
***** INSERTED 16 rows in 18ms
Ricky81682           | User:Bjimba/test looney tunes  | blanked page                  
Hmains               | Black Moshannon Creek          | /* External links */copyedit,r
Northamerica1000     | Mr. T Cereal                   |                               
Hmains               | Black Run (Paxton Creek)       | /* References */copyedit,refin
Elizium23            | List of people beatified by Po | Reverted [[WP:AGF|good faith]]
KasparBot            | Æthelsige                      | migrating [[Wikipedia:Personda
BattyBot             | Talk:Workers' Memorial Day     | /* top */[[WP:AWB/GF#Talk page
Hmains               | Black Run (West Branch Susqueh | /* References */copyedit,refin
Citobun              | Ten Years (film)               |                               
Rafe87               | User talk:Jytdog               | Undid revision 705895241 by [[
Ferdy Vahlevin       | User:Ferdy Vahlevin/sandbox    | /* Elimination Chart */       
Hmains               | Blacklog Creek                 | /* References */copyedit,refin
27.251.99.148        | Fergusson College              | /* Association with Indian pol
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read EINVAL
    at exports._errnoException (util.js:856:11)
    at TLSWrap.onread (net.js:544:26)
```

**Comment by Barbarrosa** [comment]
This time it happened immediately after requesting diffs from Wikipedia.

```
***** Requesting 20 diffs from Wikipedia
Hempanicker          | User:Hempanicker/sandbox/A.R.R |                               
***** Wikipedia returned in 0.48s
WikiwahBV            | I Saw the Light (film)         |                               
***** INSERTED 14 rows in 12ms
83.203.130.58        | Pointe-à-Pitre International A | /* Airlines and destinations *
Rms125a@hotmail.com  | St Philip Howard Catholic High | linkrot tag added             
BattyBot             | Talk:Sports Time               | /* top */[[WP:AWB/GF#Talk page
Jweiss11             | List of MCLA teams             | /* External links */ rem gener
ThE~fUtUrE~2014      | Gray wolf                      | /* Anatomy and dimensions{{anc
King of Hearts       | Invincible (Deuce album)       | more specific section         
FeatherPluma         | Number of guns per capita by c | /* List of countries by number
Cyberbot I           | Book talk:Arduino              | Updated [[User:Cyberbot I/Book
Kalope               | Talk:Ed Sheeran                | New talk section: Having the n
WP 1.0 bot           | User:WP 1.0 bot/Tables/Project | Copying assessment table to wi
Geraldo Perez        | Sonic X                        | Undid revision 698520716 by [[
69.132.212.196       | Salu Digby                     | Des                           
009o9                | User:009o9/sandbox             | /* Lottery */                 
73.43.119.140        | February 11–17, 2014 North Ame | /* Damage */                  
KasparBot            | Patrick Newell                 | migrating [[Wikipedia:Personda
***** Requesting 23 diffs from Wikipedia
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read EINVAL
    at exports._errnoException (util.js:856:11)
    at TLSWrap.onread (net.js:544:26)
```
