### ISSUE TITLE
Error: not opened in WebSocket.send

### ISSUE THREAD

**Issue by ameliabradley** [leebradley/wikiedit-monitor#20]
Wikiedit Monitor threw this error and crashed. Ideally all exceptions should be handled, even problems stemming from library dependencies.

```
Daoxford1            | 2015–16 Arkansas Razorbacks me | /* Roster */
KasparBot            | Rima Wakarua                   | migrating [[Wikipedia:Personda
White Arabian Filly  | Miniature cattle               | Bold title
***** Requesting 50 diffs from Wikipedia
Brennamarielies      | User:Brennamarielies/sandbox   |
elephanthunter@virtual-avocado:~/wikiedit-monitor$ nodejs lookup.js
Zppix                | Wikipedia:Requests for page pr | Requesting semi-protection of
A Thousand Doors     | The Dance Years                | Undid 3 revisions by [[Special
Cyberbot II          | Harrisburg, Pennsylvania       | Rescuing 1 sources. #IABot
ClueBot NG           | Freestyle scootering           | Reverting possible vandalism b
***** Requesting 50 diffs from Wikipedia
176.251.236.177      | Scott Quigg                    |
Jaisondlovu          | Mbizo Stadium                  | {{Kwekwe District}}
***** Wikipedia returned in 0.37s
Cyberbot II          | Talk:Harrisburg, Pennsylvania  | Notification of altered source
***** INSERTED 1 rows in 65ms
KasparBot            | Randy Hahn                     | migrating [[Wikipedia:Personda
D'Ranged 1           | Jagiellońska street in Bydgosz | best guess? issued=access-date
GimmeThatBook-Michae | Talk:International organ donor |
               ^
Error: not opened
    at WebSocket.send (/home/elephanthunter/wikiedit-monitor/node_modules/socket.io-client/node_modules/ws/lib/WebSocket.js:181:16)
    at Transport.WS.send (/home/elephanthunter/wikiedit-monitor/node_modules/socket.io-client/lib/transports/websocket.js:95:20)
    at Transport.packet (/home/elephanthunter/wikiedit-monitor/node_modules/socket.io-client/lib/transport.js:163:10)
    at Socket.packet (/home/elephanthunter/wikiedit-monitor/node_modules/socket.io-client/lib/socket.js:290:22)
    at SocketNamespace.packet (/home/elephanthunter/wikiedit-monitor/node_modules/socket.io-client/lib/namespace.js:64:17)
    at reset (/home/elephanthunter/wikiedit-monitor/node_modules/socket.io-client/lib/socket.js:485:34)
    at Socket.maybeReconnect (/home/elephanthunter/wikiedit-monitor/node_modules/socket.io-client/lib/socket.js:512:16)
    at Socket.EventEmitter.emit (/home/elephanthunter/wikiedit-monitor/node_modules/socket.io-client/lib/events.js:172:22)
    at Socket.onConnect (/home/elephanthunter/wikiedit-monitor/node_modules/socket.io-client/lib/socket.js:384:12)
    at Transport.onConnect (/home/elephanthunter/wikiedit-monitor/node_modules/socket.io-client/lib/transport.js:124:17)
```

**Comment by r4j4h** [comment]
Socket.io, while nice, apparently has outstanding bugs that may be muddying the waters a bit.

There is a real-time framework adapter named Primus designed to work with an array of projects, including Socket.io, and they suggest using their patched socket.io 0.9 node.js client version because it includes some bugfixes over the vanilla variant.

According to [this section from Primus.io's README on using it around Socket.io](https://github.com/primus/primus#socketio), `socket.io-client` 0.9 ([the version wikiedit-monitor uses](https://github.com/leebradley/wikiedit-monitor/blob/master/package.json#L13)) is no longer supported and contains bugs. [editlog.js uses socket.io-client](https://github.com/leebradley/wikiedit-monitor/blob/46135bccc0486b8300b1f01bc2ae5e8f90b6f9f9/editlog.js#L6).

> If you want to use the client interface inside of Node.js you also need to install the primus-socket.io-client module. This a fork of socket.io-client maintained by us to fix the bugs found on the 0.9 branch which is no longer supported upstream:
> 
> `npm install primus-socket.io-client --save`

I wonder if wikiedit-monitor would benefit from using primus' `primus-socket.io-client`?
